options:
  title: {default: My Title, description: A descriptive title used for the service., type: str}
  outlook: {description: No default outlook., type: str}
  username: {default: admin001, description: The name of the initial account (given admin permissions)., type: regex, validator: '\w{8}'}
  skill-level: {description: A number indicating skill., type: int}
