options:
  chaos-dir:
    type: string
    default: /home/ubuntu/chaos-monkey
    description: The chaos-monkey project directory.
  chaos-source:
    type: string
    default: https://github.com/juju/chaos-monkey/archive/master.tar.gz
    description: URL to Chaos Monkey source as a gzip'd compressed tar archive.
  dry-run:
    type: boolean
    default: false
    description: If set to true only log what would happen.
