options:
  chaos-dir:
    type: string
    default: /home/ubuntu/chaos-monkey
    description: The chaos-monkey project directory.
  dry-run:
    type: boolean
    default: false
    description: If set to true only log what would happen.
